<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleExecutable</key>
	<string>${EXECUTABLE_NAME}</string>
	<key>CFBundleIconFile</key>
	<string>${ASSETCATALOG_COMPILER_APPICON_NAME}</string>
	<key>CFBundleIdentifier</key>
	<string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>${QMAKE_PKGINFO_TYPEINFO}</string>
	<key>LSMinimumSystemVersion</key>
	<string>${MACOSX_DEPLOYMENT_TARGET}</string>
	<key>NOTE</key>
	<string>This file was generated by Qt/QMake.</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<!-- Required for CoreBluetooth (Qt Bluetooth's macOS backend) to be
	     allowed to scan/connect at all -- without this key macOS silently
	     denies Bluetooth access and QLowEnergyController never gets past
	     "not powered on"/"unauthorized", which reads as a mysterious BLE
	     failure with no error dialog to explain it. -->
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>qFlipper uses Bluetooth to connect to a Flipper Zero over BLE, as an alternative to the USB cable.</string>
</dict>
</plist>
